### ISSUE TITLE
Populate script issue

### ISSUE THREAD

**Issue by EdwKing** [sealneaward/template-js#1]
Tried to run the populate script on windows, 
```javascript
npm run populate
```
![picture of error](http://i.imgur.com/UDw1cIX.png)

Running the script on a new installation of MySQL workbench on linux did not give any error and worked out of the box, unsure if it's a faulty installation with the windows programs or not, will test on different laptops.

**Comment by sealneaward** [comment]
I will look into this and post some questions about the installation to you. I will try and update the windows installation too with more detail around the MySQL installation. This is probably the error point.

**Comment by sealneaward** [comment]
Hey @EdwKing can you take a look at the instructions now? I've added more detail.

https://github.com/sealneaward/template-js/blob/master/README.md

**Comment by sealneaward** [comment]
@EdwKing I think you may not have added a 'root' user, but only added the password information for the admin user that is the default in installation. This step is key and was probably missed due to the readme not explicitly outlining this. 

You will need to fully add a 'root' user, or reinstall mysql as the steps show.

Closing this for now. Reopen if this is not the issue.
